name: CI

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '12.14.1'
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build
